import type { Metadata } from "next";
import "./globals.scss";
import { AnimatePresence } from "framer-motion";


export const metadata: Metadata = {
  title: "Thigas.dev",
  description: "Generated by Thiago",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <AnimatePresence>
        {children}
        </AnimatePresence>
      </body>
    </html>
  );
}
